// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvifaxjfpaunoglcgbvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2aWZheGpmcGF1bm9nbGNnYnZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjA3OTcsImV4cCI6MjA2OTM5Njc5N30.dmy3L0ggi1R-Nd3-2cNS2prGQnmjOTu8KCnBSnHUbno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});